---
- name: Deploy Logstash
  hosts: nodes
  roles:
  - role: logstash-job-openshift
    debug: "true"
    configs_dir: "{{ inventory_dir }}/../logstash-configs/"
    logstash_project: test-anton
    kubeconfig: /home/centos/.kube/config
    job_name: job-1
