---
- name: delete items
  shell: "oc delete {{ item }} || true"
  with_items:
  - all --selector app=logstash
  - templates logstash-template
  - configmap logstash-config
  - configmap logstash-patterns
  - configmap types.db

- name: "Delete tmp files from remote"
  file: path=/tmp/{{ item }} state=absent
  with_items:
  - logstash-template.yaml
  - conf.d
  - patterns.d
