---
- fail:
    msg: "logstash_project variable must be set to logstash namespace"
  when: logstash_project is undefined

# allow passing in a tempdir
- name: Create temp directory for doing work in
  command: mktemp -d /tmp/container-logstash-XXXXXX
  register: mktemp
  changed_when: False

- set_fact:
    tempdir: "{{ mktemp.stdout }}"

# Set up PVC for persistent queue
- name: "Copy Queue PVC declaration to the remote"
  template:
    src: logstash-queue.yaml.j2
    dest: '{{ tempdir }}/logstash-queue.yaml'
  changed_when: no

- name: "Create Queue PVC"
  shell: 'oc apply -f {{ tempdir }}/logstash-queue.yaml  -n {{ logstash_project }}'

# Logstash conf.d Configmap
- name: Create temp directory for configs
  file:
    path: '{{ tempdir }}/conf.d/'
    state: directory
    mode: 0755

- name: "Copy logstash client configs to the remote"
  template:
    src: '{{ item }}'
    dest: '{{ tempdir }}/conf.d/'
  with_fileglob:
  - "{{ configs_dir }}/conf.d/*"
  changed_when: no

- name: Set Logstash client configmaps
  oc_configmap:
    state: present
    name: logstash-config
    namespace: "{{ logstash_project }}"
    kubeconfig: '{{ kubeconfig }}'
    from_dir: '{{ tempdir }}/conf.d/'

# Logstash patterns.d configmap
- name: "Copy logstash patterns to the remote"
  copy:
    src: '{{ item }}'
    dest: '{{ tempdir }}/patterns.d/'
  with_fileglob:
  - "{{ configs_dir }}/patterns.d/*"
  changed_when: no

- name: Set Logstash client patterns
  oc_configmap:
    state: present
    name: logstash-patterns
    namespace: "{{ logstash_project }}"
    kubeconfig: '{{ kubeconfig }}'
    from_dir: '{{ tempdir }}/patterns.d/'

# Create secrets from Logstash certs
- name: Use certificates
  include: "{{ role_path }}/tasks/upload_certs.yaml"
  when: certs_dir is defined

# Logstash Job
- name: "Copy Logstash job template to the remote"
  template:
    src: 'logstash-job.yaml.j2'
    dest: '{{ tempdir }}/logstash-job.yaml'
  changed_when: no

- name: "Create Logstash infrastructure template"
  shell: oc apply -f {{ tempdir }}/logstash-job.yaml  -n {{ logstash_project }}

- name: Delete temp directory
  file:
    name: "{{ tempdir }}"
    state: absent
  changed_when: False
